# Get the cost of a plan in the 3D costmap.
# The first two fields are identical to nav_msgs/Path
Header header
geometry_msgs/PoseStamped[] poses

# If true, stop as soon as a lethal pose is found.
# Poses are processed in order, and when a lethal pose is found
# no further processing is done.
bool lazy

# If true, run this query on a copy of the costmap, leaving it unlocked
# after copy. If false, run directly on the master costmap, leaving it locked
# for the duration of the query.
bool buffered

# Return costs of each pose as normal
uint8 COST_QUERY_MODE_COST=0
# Do not find actual costs, just binary collision information
uint8 COST_QUERY_MODE_COLLISION_ONLY=1
# Do not find actual costs, find distances instead
uint8 COST_QUERY_MODE_DISTANCE=2
# Do not find actual costs, find signed distances instead
# Note that signed distance may not be exact, but approximated.
# However, signed distance must have the property that querying small changes
# in position/orientation will generate a derivative pointing away from
# one of the penetration points (not necessarily the deepest).
uint8 COST_QUERY_MODE_SIGNED_DISTANCE=3
# Set to one of the above COST_QUERY_MODE_* to control query mode.
# The default is COST_QUERY_MODE_COST.
uint8 cost_query_mode

# Query entire map
uint8 COST_QUERY_REGION_ALL=0
# Query the map only to the left of each query pose.
uint8 COST_QUERY_REGION_LEFT=1
# Query the map only to the right of each query pose.
uint8 COST_QUERY_REGION_RIGHT=2
# Query a 1m by 1m rectangular prism starting at the origin of each pose.
# To alter the size of the prism in the frame of the pose, scale the
# pose's quaternion appropriately to scale the prism when it is transformed.
# To scale the width differently from the height, use the ray query interface.
uint8 COST_QUERY_REGION_RECTANGULAR_PRISM=3
# Set to one of the above COST_QUERY_REGION_* to control query region per pose.
# If the region is missing for a given pose, COST_QUERY_REGION_ALL is assumed.
uint8[] cost_query_regions

# Query only lethal obstacles (default)
uint8 COST_QUERY_OBSTACLES_LETHAL_ONLY=0
# Query only nonlethal obstacles. Nonlethal is any cell that is between FREE and LETHAL.
uint8 COST_QUERY_OBSTACLES_NONLETHAL_ONLY=1
# Set to one of the above COST_QUERY_OBSTACLES_* to control what costs are
# considered during a query. In lethal only, only lethal obstacles are
# considered. In nonlethal only, only nonlethal (cost between FREE and LETHAL)
# are considered. Other modes may be added to this list at a later time as they
# are implemented.
uint8[] cost_query_obstacles

# An alternative footprint_mesh_resource to use (in base_footprint frame)
# If empty, the default stored in the costmap will be used.
string footprint_mesh_resource

# How much padding (in meters) to grow the footprint mesh.
# (negative numbers will shrink the mesh).
# 0.0 means no padding.
# NaN means use the default value from the costmap.
# To precisely control padding, use an alternate mesh, as the generated mesh
# may pad in a naive way.
float32 padding

# The maximum amount of time (seconds) to wait for a transform to become
# available to transform a pose. (default=0.1, any values <= 0 will be
# converted to the default.)
float32 transform_wait_time_limit
---
# The aggregate cost value across the poses.
# A negative cost value indicates collision.
# A cost value of 0.0 means no cost.
# A postive cost value indicates non-zero, yet non-lethal cost.
# When running in one of the distance modes, the plan_cost will be the minimum
# distance across all the poses. Note that all forms of distance check will return
# a negative distance for a collision, but only in the exact signed mode will
# the negative value be an exact signed distance.
float64 cost
# The cost of each pose.
# When running in one of the distance modes, the "cost" will instead be the
# distance to the nearest obstacle in meters.
float64[] pose_costs
uint32[] lethal_indices
