geometry_msgs/PoseStamped start
geometry_msgs/PoseStamped goal
---

uint8 plan_found
string error_message

# if plan_found is true, this is an array of waypoints from start to goal, where the first one equals start and the last one equals goal
geometry_msgs/PoseStamped[] path
