#
# Makefile for navigation function planner
#

CC = g++
CXX = g++
LD = g++
CPPFLAGS = -Wall -g -O3 -Iinclude -I/usr/local/include -I/usr/local/include/opencv
CFLAGS = -DGCC -msse2 -mpreferred-stack-boundary=4 -O3 -Wall -Iinclude -I/usr/local/include
GCC = g++
LDFLAGS = -Lbin 
SHAREDFLAGS = -shared -Wl,-soname,
LIBS = -lfltk -lnetpbm

OBJECTS = navfn navwin

all:	bin/navtest

bin/navtest: obj/navtest.o $(OBJECTS:%=obj/%.o)
	$(LD) $(LDFLAGS) -o $@ $(OBJECTS:%=obj/%.o) obj/navtest.o $(LIBS)

# general cpp command from src->obj
obj/%.o:src/%.cpp
	$(GCC) $(CPPFLAGS) -c $< -o $@

# general c command from src->obj
obj/%.o:src/%.c
	$(GCC) $(CFLAGS) -c $< -o $@

obj/navfn.o: include/navfn/navfn.h

clean:
	- rm obj/*.o
	- rm bin/navtest

dist:



